INSERT INTO `DISTRICT`(`DS_ID`, `DS_NAME`, `DS_CODE`, `ST_ID`) VALUES ('1','Bagalkot','',12);
INSERT INTO `DISTRICT`(`DS_ID`, `DS_NAME`, `DS_CODE`, `ST_ID`) VALUES ('2','Belagavi','',12);
INSERT INTO `DISTRICT`(`DS_ID`, `DS_NAME`, `DS_CODE`, `ST_ID`) VALUES ('3','Bellary','',12);
INSERT INTO `DISTRICT`(`DS_ID`, `DS_NAME`, `DS_CODE`, `ST_ID`) VALUES ('4','Bengaluru Rural','',12);
INSERT INTO `DISTRICT`(`DS_ID`, `DS_NAME`, `DS_CODE`, `ST_ID`) VALUES ('5','Bengaluru Urban','',12);
INSERT INTO `DISTRICT`(`DS_ID`, `DS_NAME`, `DS_CODE`, `ST_ID`) VALUES ('6','Bidar','',12);
INSERT INTO `DISTRICT`(`DS_ID`, `DS_NAME`, `DS_CODE`, `ST_ID`) VALUES ('7','Chamarajanagar','',12);
INSERT INTO `DISTRICT`(`DS_ID`, `DS_NAME`, `DS_CODE`, `ST_ID`) VALUES ('8','Chikballapur','',12);
INSERT INTO `DISTRICT`(`DS_ID`, `DS_NAME`, `DS_CODE`, `ST_ID`) VALUES ('9','Chikkamagaluru','',12);
INSERT INTO `DISTRICT`(`DS_ID`, `DS_NAME`, `DS_CODE`, `ST_ID`) VALUES ('0','Chitradurga','',12);
INSERT INTO `DISTRICT`(`DS_ID`, `DS_NAME`, `DS_CODE`, `ST_ID`) VALUES ('11','Dakshina Kannada','',12);
INSERT INTO `DISTRICT`(`DS_ID`, `DS_NAME`, `DS_CODE`, `ST_ID`) VALUES ('12','Davanagere','',12);
INSERT INTO `DISTRICT`(`DS_ID`, `DS_NAME`, `DS_CODE`, `ST_ID`) VALUES ('13','Dharwad','',12);
INSERT INTO `DISTRICT`(`DS_ID`, `DS_NAME`, `DS_CODE`, `ST_ID`) VALUES ('14','Gadag','',12);
INSERT INTO `DISTRICT`(`DS_ID`, `DS_NAME`, `DS_CODE`, `ST_ID`) VALUES ('15','Hassan','',12);
INSERT INTO `DISTRICT`(`DS_ID`, `DS_NAME`, `DS_CODE`, `ST_ID`) VALUES ('16','Haveri','',12);
INSERT INTO `DISTRICT`(`DS_ID`, `DS_NAME`, `DS_CODE`, `ST_ID`) VALUES ('17','Kalaburagi','',12);
INSERT INTO `DISTRICT`(`DS_ID`, `DS_NAME`, `DS_CODE`, `ST_ID`) VALUES ('18','Kodagu','',12);
INSERT INTO `DISTRICT`(`DS_ID`, `DS_NAME`, `DS_CODE`, `ST_ID`) VALUES ('19','Kolar','',12);
INSERT INTO `DISTRICT`(`DS_ID`, `DS_NAME`, `DS_CODE`, `ST_ID`) VALUES ('20','Koppal','',12);
INSERT INTO `DISTRICT`(`DS_ID`, `DS_NAME`, `DS_CODE`, `ST_ID`) VALUES ('21','Mandya','',12);
INSERT INTO `DISTRICT`(`DS_ID`, `DS_NAME`, `DS_CODE`, `ST_ID`) VALUES ('22','Mysuru','',12);
INSERT INTO `DISTRICT`(`DS_ID`, `DS_NAME`, `DS_CODE`, `ST_ID`) VALUES ('23','Raichur','',12);
INSERT INTO `DISTRICT`(`DS_ID`, `DS_NAME`, `DS_CODE`, `ST_ID`) VALUES ('24','Ramanagara','',12);
INSERT INTO `DISTRICT`(`DS_ID`, `DS_NAME`, `DS_CODE`, `ST_ID`) VALUES ('25','Shivamogga','',12);
INSERT INTO `DISTRICT`(`DS_ID`, `DS_NAME`, `DS_CODE`, `ST_ID`) VALUES ('26','Tumakuru','',12);
INSERT INTO `DISTRICT`(`DS_ID`, `DS_NAME`, `DS_CODE`, `ST_ID`) VALUES ('27','Udupi','',12);
INSERT INTO `DISTRICT`(`DS_ID`, `DS_NAME`, `DS_CODE`, `ST_ID`) VALUES ('28','Uttara Kannada','',12);
INSERT INTO `DISTRICT`(`DS_ID`, `DS_NAME`, `DS_CODE`, `ST_ID`) VALUES ('29','Vijayapura','',12);
INSERT INTO `DISTRICT`(`DS_ID`, `DS_NAME`, `DS_CODE`, `ST_ID`) VALUES ('30','Yadgir','',12);


INSERT INTO `DISTRICT`(`DS_ID`, `DS_NAME`, `DS_CODE`, `ST_ID`) VALUES ('','','',12);
1
2
3
4
5
6
7
8
9
0
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30